create table if not exists public.profile_votes (
  id bigint generated by default as identity primary key,
  profile_id integer not null check (profile_id between 1 and 40),
  aura_points integer not null default 0 check (aura_points between 98000 and 103000),
  created_at timestamptz not null default now()
);

create or replace view public.profile_vote_totals as
select profile_id, count(*)::integer as total_votes
from public.profile_votes group by profile_id;

create or replace view public.profile_aura_totals as
select profile_id, coalesce(sum(aura_points), 0)::integer as aura
from public.profile_votes group by profile_id;

alter table public.profile_votes enable row level security;
create policy "public can submit profile votes" on public.profile_votes
  for insert to anon, authenticated with check (profile_id between 1 and 40);
create policy "public can read vote totals" on public.profile_votes
  for select to anon, authenticated using (true);
