create table if not exists public.teacher_ratings (
  id bigint generated by default as identity primary key,
  session_id text not null,
  profile_id integer not null check (profile_id between 1 and 40),
  lesson integer not null check (lesson between 1 and 5),
  productivity integer not null check (productivity between 1 and 5),
  atmosphere integer not null check (atmosphere between 1 and 5),
  score integer not null check (score between 0 and 1000000),
  rated_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (session_id, profile_id, rated_on)
);

create or replace view public.teacher_score_totals as
select profile_id, round(avg(score))::integer as score
from public.teacher_ratings
group by profile_id;

alter table public.teacher_ratings enable row level security;
create policy "public can submit teacher ratings" on public.teacher_ratings
  for insert to anon, authenticated with check (profile_id between 1 and 40 and lesson between 1 and 5 and productivity between 1 and 5 and atmosphere between 1 and 5);
create policy "public can update teacher ratings" on public.teacher_ratings
  for update to anon, authenticated using (true) with check (profile_id between 1 and 40);
create policy "public can read teacher scores" on public.teacher_ratings
  for select to anon, authenticated using (true);
